# 1. ETL and analysis for e-commerce big data

##### Jeff Guo; Aug 16, 2016; guojianfu@gmail.com

## 1.1 Working on missing data

At first, when we get the raw data, they are usually excel files, csv files or MySQL tables. Here we focus on excel files. Csv files are similar. MySQL tables are treated just like what we do after we finish ETL process and build up the data warehouse.

Raw data and real data (not simulated data) usually contain missing data, here we first try to detect the missing data. After we put the raw data into python pandas dataframe, the missing data will be denotated as np.NaN, which can be detected by isnull(). np.NaN is a float number, which occupies less space than None (None is an object).

Show sheet names of an excel:  
pd.ExcelFile("dognition_data_aggregated_by_dogid.xlsx").sheet_names  
pd is pandas, and xlrd is used by pandas to call ExcelFile method.

Produce a spreadsheet of an excel file:  
pd.ExcelFile("dognition_data_aggregated_by_dogid.xlsx").parse("dog_id_max_ranks")  
The result is a dataframe.
pd.read_csv() is to produce a spreadsheet of a csv file.
You can also convert a SQL table to a dataframe.

Dimentionality of a dataframe:  
pd.DataFrame(np.random.randn(10, 5)).shape  
The result ia a tuple.
np is numpy.
np.random.randn(10, 5) produeces an numpy ndarray of 10 by 5, and randn is for random variable of normal distribution.
shape is an attribution of the class DataFrame, to call this attribution may lead to the use of a method of the class.

True of False (if there is any True, if there is any null):  
pd.DataFrame(np.random.randn(10, 5)).isnull().values.any()

Total number of 'True':  
pd.DataFrame(np.random.randn(10, 5)).isnull().sum().sum()

True numbers of each column:  
pd.DataFrame(np.random.randn(10, 5)).isnull().sum()  
The result is a Series.

In [1]:
import numpy as np
import pandas as pd

a=np.random.randn(10, 5)
print a
print type(a)

b=pd.DataFrame(a)
# from an array to a dataframe, an array with row names and column names
print b
print type(b)

print b.head()
print b.dtypes
# the data types of the columns
print b.columns.dtype
# np.int64, the data type of column names
print b[0].dtype
# np.float64, b[0] is the column 0

c={'one':[1.,2.,3.,4.],\
   'two':[4.,3.,2.,1.]} # this line continuation backslash is optional
d=pd.DataFrame(c)
# from a dict to a dataframe
print d

e=pd.DataFrame(c, index=['a', 'b', 'c', 'd'])
# index is equivalent to the row names
print e
print type(e.index)
# index is a class
print e.index
# it is an object of the index class

f=pd.DataFrame(a, columns=['a', 'b', 'c', 'd', 'e'])
print f.columns
print f.columns.dtype
# index object

print pd.DataFrame(np.random.randn(10, 5)).isnull().values
# .values makes a dataframe to convert to an array
print type(pd.DataFrame(np.random.randn(10, 5)).isnull().values)
s = pd.Series([1, 2, 3, np.NaN, 5, 6, None])
# np.NaN, None, from a list to a series
print type(np.NaN)
print type(None)
print s.isnull()
# a series with true or false
print s[s.isnull()]
# slice a series by a logical series

[[-0.18237677  1.12930136  0.78098967 -0.25690122  0.60139296]
 [-1.32033849  0.57682164  1.44615277  2.70351033  0.12633422]
 [-0.82579123  0.35671013 -0.98564813  0.0590451  -0.29191429]
 [ 1.76798502  0.28320346  0.7608162  -1.01699486  1.31762646]
 [-0.27244828 -0.07973371  0.65838305 -1.63093337 -1.11955678]
 [-1.00163091 -0.58785405  1.45967343 -1.02164385  1.23169053]
 [ 0.89775739 -0.17175646  1.54990679 -1.07711296 -1.14414369]
 [-0.81543845 -1.12225662  0.36969402  0.04794962 -0.10807063]
 [-0.83773462 -1.56189653 -0.28647936 -0.23256819  0.73242114]
 [ 0.55039421 -0.00599683 -0.97200376  0.31203117 -0.05256487]]
<type 'numpy.ndarray'>
          0         1         2         3         4
0 -0.182377  1.129301  0.780990 -0.256901  0.601393
1 -1.320338  0.576822  1.446153  2.703510  0.126334
2 -0.825791  0.356710 -0.985648  0.059045 -0.291914
3  1.767985  0.283203  0.760816 -1.016995  1.317626
4 -0.272448 -0.079734  0.658383 -1.630933 -1.119557
5 -1.001631 -0.587854  1.459673 -1.021644  1.231691
6  0.897757 -0.171756  1.549907 -1.077113 -1.144144
7 -0.815438 -1.122257  0.369694  0.047950 -0.108071
8 -0.837735 -1.561897 -0.286479 -0.232568  0.732421
9  0.550394 -0.005997 -0.972004  0.312031 -0.052565
<class 'pandas.core.frame.DataFrame'>
          0         1         2         3         4
0 -0.182377  1.129301  0.780990 -0.256901  0.601393
1 -1.320338  0.576822  1.446153  2.703510  0.126334
2 -0.825791  0.356710 -0.985648  0.059045 -0.291914
3  1.767985  0.283203  0.760816 -1.016995  1.317626
4 -0.272448 -0.079734  0.658383 -1.630933 -1.119557
0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object
int64
float64
   one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0
   one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  1.0
<class 'pandas.indexes.base.Index'>
Index([u'a', u'b', u'c', u'd'], dtype='object')
Index([u'a', u'b', u'c', u'd', u'e'], dtype='object')
object
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
<type 'numpy.ndarray'>
<type 'float'>
<type 'NoneType'>
0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool
3   NaN
6   NaN
dtype: float64

In [21]:
import pandas as pd
xl = pd.ExcelFile("dognition_data_aggregated_by_dogid.xlsx")
# xlrd is used by pandas
xl.sheet_names
df = xl.parse("dog_id_max_ranks")
# produce a dataframe
# df.head()

print df.shape
print
print df.isnull().values.any()
print
print df.isnull().sum().sum()
print
print df.isnull().sum()
print
print df.isnull().sum().index

print type(df.isnull().sum())
# every series has a dtype attribution

(17986, 30)

True

30500

Dog ID                                                0
Total Tests Completed                                 0
Mean ITI (days)                                    1268
Mean ITI (minutes)                                 1268
Median ITI (days)                                  1268
Median ITI (minutes)                               1268
Time diff between first and last game (days)          0
Time diff between first and last game (minutes)       0
User ID                                               1
Gender                                                1
Birthday                                              1
Breed                                                16
Breed_Type                                            1
Breed_Group                                           1
Weight                                                1
Dog_Fixed                                             1
DNA_Tested                                            1
Dimension                                             1
Sign_in_Count                                         1
Max_Dogs                                              1
Membership_ID                                         1
Subscribed                                            1
City                                               6368
State                                              6363
Zip                                                6396
Country                                            6268
Exclude                                               1
Free_Start_User                                       1
Last_Active_At                                        1
Membership_Type                                       1
dtype: int64

Index([u'Dog ID', u'Total Tests Completed', u'Mean ITI (days)',
       u'Mean ITI (minutes)', u'Median ITI (days)', u'Median ITI (minutes)',
       u'Time diff between first and last game (days)',
       u'Time diff between first and last game (minutes)', u'User ID',
       u'Gender', u'Birthday', u'Breed', u'Breed_Type', u'Breed_Group',
       u'Weight', u'Dog_Fixed', u'DNA_Tested', u'Dimension', u'Sign_in_Count',
       u'Max_Dogs', u'Membership_ID', u'Subscribed', u'City', u'State', u'Zip',
       u'Country', u'Exclude', u'Free_Start_User', u'Last_Active_At',
       u'Membership_Type'],
      dtype='object')
<class 'pandas.core.series.Series'>

Produce the dataframe:  
df=pd.ExcelFile("dognition_data_aggregated_by_dogid.xlsx").parse("dog_id_max_ranks")

True numbers of each row, too many rows:  
np.sum(df.isnull().values, axis = 1)

The range of Ture numbers for the rows:  
[min(np.sum(df.isnull().values, axis = 1)), max(np.sum(df.isnull().values, axis = 1))]

From a numpy ndarray to a list:  
num = np.sum(df.isnull().values, axis = 1).tolist()

Get unique values of the list and sort the list:  
l1 = list(set(num))
l1.sort()

list comprehension and put the results in a dict:  
fre = {i:num.count(i) for i in l1}  
count() is a method in the list class

Row counts for 'Number of NaNs', construct a dataframe from a dict:  
pd.DataFrame(fre.items(), columns=['Number of NaNs', 'Count'])  
Row index is row numbers.

In [16]:
import numpy as np

# np.ptp(np.sum(df.isnull().values, axis = 1), axis=0)
print [min(np.sum(df.isnull().values, axis = 1)), max(np.sum(df.isnull().values, axis = 1))]
# df.isnull().values is an array, np.sum(,axis=1) means sum the values of each row
print

num = np.sum(df.isnull().values, axis = 1).tolist()
# from a 1D numpy array to a list

l1 = list(set(num))
l1.sort()
# get unique values of a list and sort

fre = {i:num.count(i) for i in l1}
# list comprehension to replace for loop
# count is a method of list
# the result of list comprehension can be put in a dict
# print fre
# print

dt = pd.DataFrame(fre.items(), columns=['Number of NaNs', 'Count'])
# dict.items() can convert a dict to a 2D list
# or list(fre.items()) in python 3

print dt

ts = pd.DataFrame(np.sum(df.isnull().values, axis = 1))
print type(ts)
# ts is a 1D dataframe
# print ts
print ts[0].value_counts()
print type(ts[0].value_counts())
# series
print ts[0].value_counts().name
ts2 = pd.Series(np.sum(df.isnull().values, axis = 1))
print type(ts2)
# series
print ts2.value_counts()
print ts2.value_counts().dtype
print ts2.value_counts().name

[0, 22]

   Number of NaNs  Count
0               0  11145
1               1     46
2               2     19
3               3     89
4               4   5832
5               5      8
6               7      9
7               8    837
8              22      1
<class 'pandas.core.frame.DataFrame'>
0     11145
4      5832
8       837
3        89
1        46
2        19
7         9
5         8
22        1
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>
0
<class 'pandas.core.series.Series'>
0     11145
4      5832
8       837
3        89
1        46
2        19
7         9
5         8
22        1
dtype: int64
int64
None

We can draw and save tables to pictures in python.  
missingData.ipynb has the code to draw pictures.

We can also save json data and then apply the data to a html template with python to produce table in a webpage.

In [19]:
import numpy as np

x = [1, 2, 3]
y = [4, 5, 6]
zipped = zip(x, y)
print zipped
# from two lists to form a 2D list
print type(zipped)

print zip((1,4),(2,5),(3,6))
print zip([1,4],[2,5])

x2, y2 = zip(*zip(x, y))
# There are two ways to use *, one way is to use it as function parameter, and another way is
# to use it as function argument. It's the same to **, the differences are * is for list, while
# ** is for dict.
# If you have a list of arguments, *args, it's called "argument unpacking", 
# in the same manner **kwargs is called "keyword argument unpacking".
print type(x2)
print x == list(x2) and y == list(y2)

s=df.isnull().sum()
print type(s)
print s.name
print np.array(dt).tolist()
# from a dataframe to a list
# np array and np ndarray

data_rows=np.array(dt).tolist()
# from a 2D dataframe to a list
dict_rows={x:y for x,y in data_rows}
# from a 2D dataframe to a dict
print dict_rows

[(1, 4), (2, 5), (3, 6)]
<type 'list'>
[(1, 2, 3), (4, 5, 6)]
[(1, 2), (4, 5)]
<type 'tuple'>
True
<class 'pandas.core.series.Series'>
None
[[0, 11145], [1, 46], [2, 19], [3, 89], [4, 5832], [5, 8], [7, 9], [8, 837], [22, 1]]
{0: 11145, 1: 46, 2: 19, 3: 89, 4: 5832, 5: 8, 7: 9, 8: 837, 22: 1}

In [20]:
import json

s=df.isnull().sum()
s.tolist()
s.index.tolist()
# Dataframe has no method of tolist(), but series has a method of tolist()

data_columns=dict(zip(s.index.tolist(),s.tolist()))
print data_columns
# from a series to a dict; the same can be done from a dataframe to a dict
# in python 2, there are strings and unicodes (utf-8).

with open('data_columns.json','w') as nnFile:
    json.dump(data_columns, nnFile)
# data_columns is a dict    
# command+[ is for block indent

data_rows=np.array(dt).tolist()
# from a 2D dataframe to a list
with open('data_rows.json','w') as nnFile:
    json.dump(data_rows, nnFile)
# data_rows is a list

{u'Membership_Type': 1, u'City': 6368, u'Subscribed': 1, u'Breed_Type': 1, u'Breed': 16, u'Membership_ID': 1, u'Last_Active_At': 1, u'State': 6363, u'Sign_in_Count': 1, u'Zip': 6396, u'Mean ITI (days)': 1268, u'User ID': 1, u'Country': 6268, u'Max_Dogs': 1, u'Median ITI (minutes)': 1268, u'Total Tests Completed': 0, u'Mean ITI (minutes)': 1268, u'Dog ID': 0, u'Gender': 1, u'DNA_Tested': 1, u'Dog_Fixed': 1, u'Exclude': 1, u'Breed_Group': 1, u'Dimension': 1, u'Free_Start_User': 1, u'Median ITI (days)': 1268, u'Weight': 1, u'Time diff between first and last game (minutes)': 0, u'Time diff between first and last game (days)': 0, u'Birthday': 1}